os: linux
dist: focal
language: java

addons:
  apt:
    packages:
      - ant
      - curl
      - unzip

services:
  - docker

before_install:
  - ant docker_run
  - npm install prettydiff
  - curl -L https://sourceforge.net/projects/saxon/files/Saxon-HE/9.9/SaxonHE9-9-1-8J.zip/download -o saxon.zip
  - unzip saxon.zip -d saxon

script:
  - ant -lib saxon test

after_failure:
  - docker cp wega:/exist/logs/exist.log .
  - tail -2000 exist.log 