sudo: required

language: java

services:
  - docker

before_install:
  - docker build -t wega .
  - docker run --name wega -d -p 8080:8080 -e WEGA_WEBAPP_dataCollectionPath="/db/apps/WeGA-data-testing" wega
  - while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8080/exist)" != "302" ]] ; do sleep 5 ; done
  - docker exec -it wega cat webapp/WEB-INF/logs/exist.log

script:
  - curl -iLf  http://localhost:8080/exist/apps/WeGA-WebApp/