dist: xenial
language: java

addons:
  apt:
    packages:
      - ant
      - curl
      - libsaxonhe-java

services:
  - docker

before_install:
  - ant docker_run
  - npm install prettydiff

script:
  - ant -lib /usr/share/java test

after_failure:
  - docker exec -it wega tail -2000 webapp/WEB-INF/logs/exist.log 