sudo: required

language: java

services:
  - docker

before_install:
  - ant docker_run
  - docker cp wega:/opt/exist/lib/endorsed/Saxon-HE-9.6.0-7.jar .

script:
  - ant -lib . test

after_failure:
  - docker exec -it wega cat webapp/WEB-INF/logs/exist.log 