dist: xenial
language: java

addons:
  apt:
    packages:
      ant

services:
  - docker

before_install:
  - ant docker_run
  - npm install prettydiff
  - docker cp wega:/opt/exist/lib/endorsed/Saxon-HE-9.6.0-7.jar .

script:
  - ant -lib . test

after_failure:
  - docker exec -it wega tail -2000 webapp/WEB-INF/logs/exist.log 