name: Docker Testing

on: 
  push:
  pull_request:

jobs:
  build:
    name: build and test the Docker image
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup
        # To save time, we install not all the node dependencies but only prettydiff globally.
        # Hence, when updating prettydiff in package.json this needs to be reflected here as well.
        run: sudo apt-get install libsaxonhe-java && npm install -g prettydiff@101
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Build and run Docker image
        run: ant docker_run
      - name: Run tests
        run: ant -lib /usr/share/java -Dprettydiff.cmd=`which prettydiff` test
