name: Docker Testing

on: push

jobs:
  build:
    name: build and test the Docker image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup
        run: sudo apt-get install libsaxonhe-java && npm install prettydiff 
      - name: Build and run Docker image
        run: ant docker_run
      - name: Run tests
        run: ant -lib /usr/share/java test
