name: Docker Testing

on: 
  push:
  pull_request:

jobs:
  build:
    name: build and test the Docker image
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup
        run: sudo apt-get install libsaxonhe-java && npm install -g prettydiff@99 
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and run Docker image
        run: ant docker_run
      - name: Run tests
        run: ant -lib /usr/share/java -Dprettydiff.cmd=`which prettydiff` test
